#ifndef CRYPTOPP_GLOBAL_H
#define CRYPTOPP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CRYPTOPP_LIBRARY)
#  define CRYPTOPPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CRYPTOPPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CRYPTOPP_GLOBAL_H
